#!/bin/bash
#
# Copyright (C) 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

# This script will finalize resources and update the API signature files.
# If run locally it will pick up whatever 'lunch' target is set, and if one isn't set then it will default to `sdk-sdk_finalization-userdebug`

source "$(dirname "$0")"/common.sh

# Build finalize_res binary. It will include a copy of all_aconfig_declarations.pb that holds the state of the aconfig flags for the TARGET_RELEASE.
m finalize_res

# Finalize resources
finalize_res "$top/frameworks/base/core/res/res/values/public-staging.xml" "$top/frameworks/base/core/res/res/values/public-final.xml"

# Update signature files
m update-api
