#!/bin/bash
#
# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# resources
tmp=$(mktemp)
trap "rm -f $tmp" EXIT
m finalize_res
finalize_res \
    "$TOP/frameworks/base/core/res/res/values/public-staging.xml" \
    "$TOP/frameworks/base/core/res/res/values/public-final.xml" | tee $tmp

if grep -q -e '^0 resource(s) were finalized' $tmp; then
    pushd "$TOP/frameworks/base"
    git reset --hard
    popd
else
    m update-api
    git_commit \
        frameworks/base \
<<EOF
Re-finalize resources for Android $MAJOR.$MINOR

CL generated by running these commands:

  m finalize_res
  finalize_res \\
      \$(gettop)frameworks/base/core/res/res/values/public-staging.xml \\
      \$(gettop)frameworks/base/core/res/res/values/public-final.xml
  m update-api

Bug: $BUG
Test: N/A
Flag: NONE platform SDK finalization
EOF
fi

# mainline sdk
if [[ -z "$mainline_sdks_dir" ]]; then
    TARGET_RELEASE=sdk_finalization TARGET_BUILD_VARIANT=userdebug UNBUNDLED_BUILD_SDKS_FROM_SOURCE=true vendor/google/build/mainline_modules_sdks.sh --build-release next
    mainline_sdks_dir="$DIST_DIR"
fi

m unpack-module-sdks
projects="$(unpack-module-sdks \
    --mainline-sdks-top "$mainline_sdks_dir" \
    --android-top "$TOP" \
    --sdk-ext-version $SDK_EXT_VERSION)"

for project in $projects; do
    git_commit \
        $project \
<<EOF
Re-finalize SDK extension $SDK_EXT_VERSION

Import module SDK artifacts from ab/$BUILD_NUMBER.

Bug: $BUG
Test: N/A
Flag: NONE platform SDK finalization
EOF
done

# platform sdk
set_prospective_sdk_version_full "$MAJOR.$MINOR"
m sdk sdk_repo dist
clear_prospective_sdk_version_full

m unpack-platform-sdk
unpack-platform-sdk \
    --dist-dir "$DIST_DIR" \
    --android-top "$TOP" \
    --version "$MAJOR.$MINOR"

# jar files include timestamps that can differ; if there was any API change we'd also see differences in .txt files
if [[ -z "$(git -C "$TOP/prebuilts/sdk" ls-files --others --modified | grep -v -e '\.jar$')" ]]; then
    info "No meaningful API changes"
    pushd "$TOP/prebuilts/sdk"
    git reset --hard
    popd
else
    git_commit \
        prebuilts/sdk \
<<EOF
Re-finalize platform SDK for Android $MAJOR.$MINOR

Files imported from ab/$BUILD_NUMBER.

Bug: $BUG
Test: N/A
Flag: NONE platform SDK finalization
EOF
fi
